### ISSUE TITLE
url question about snowpack

### ISSUE THREAD

**Issue by czppzc** [benfred/venn.js#152]
When I tried to pack my project with snowpack, I found the introduced errors in diagram.js and layout.js of src of venn, , the specific errors are as follows
![image](https://user-images.githubusercontent.com/40969849/110243701-6c13f000-7f96-11eb-9817-9a045f4afcb0.png)
I hope you can modify the import path of these two files or if you can provide a good solution, thank you very much

**Comment by benfred** [comment]
Are you running the latest version? I believe this has been fixed for quite a while : https://github.com/benfred/venn.js/blob/5ff0ef3ff450803a50c69493cd2bb6ce8b04f9fb/src/diagram.js#L6

**Comment by czppzc** [comment]
> Are you running the latest version? I believe this has been fixed for quite a while :
> 
> https://github.com/benfred/venn.js/blob/5ff0ef3ff450803a50c69493cd2bb6ce8b04f9fb/src/diagram.js#L6
I have indeed used the latest version 0.2.20，but still get the wrong quote
![image](https://user-images.githubusercontent.com/40969849/123536872-51d96a00-d75f-11eb-8268-f45a3ca67f9d.png)

**Comment by czppzc** [comment]
and my system is windows
